In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print('All libraries imported successfully!')

All libraries imported successfully!

In [33]:
df = pd.read_csv('../01_Raw_Data/Amazon Sale Report.csv', low_memory=False)

print("Your data imported successfully!")

Your data imported successfully!

In [34]:
# ==========================================
#      STEP 1: DATA UNDERSTANDING
# ==========================================

In [35]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [36]:
df.tail()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,INR,517.0,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,999.0,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,INR,690.0,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.0,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,INR,696.0,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [37]:
df.shape

(128975, 24)

In [38]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='object')

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [40]:
df.dtypes

index                   int64
Order ID               object
Date                   object
Status                 object
Fulfilment             object
Sales Channel          object
ship-service-level     object
Style                  object
SKU                    object
Category               object
Size                   object
ASIN                   object
Courier Status         object
Qty                     int64
currency               object
Amount                float64
ship-city              object
ship-state             object
ship-postal-code      float64
ship-country           object
promotion-ids          object
B2B                      bool
fulfilled-by           object
Unnamed: 22            object
dtype: object

In [41]:
df.describe()

               index            Qty         Amount  ship-postal-code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

In [42]:
df.describe(include = 'object')

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,currency,ship-city,ship-state,ship-country,promotion-ids,fulfilled-by,Unnamed: 22
count,128975,128975,128975,128975,128975,128975,128975,128975,128975,128975,128975,122103,121180,128942,128942,128942,79822,39277,79925
unique,120378,91,13,2,2,2,1377,7195,9,11,7190,3,1,8955,69,1,5787,1,1
top,171-5057375-2831560,05-03-22,Shipped,Amazon,Amazon.in,Expedited,JNE3797,JNE3797-KR-L,Set,M,B09SDXFFQ1,Shipped,INR,BENGALURU,MAHARASHTRA,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,Easy Ship,False
freq,12,2085,77804,89698,128851,88615,4224,773,50284,22711,773,109487,121180,11217,22260,128942,46100,39277,79925

In [43]:
df.describe(include='all')

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
count,128975.000000,128975,128975,128975,128975,128975,128975,128975,128975,128975,...,121180,121180.000000,128942,128942,128942.000000,128942,79822,128975,39277,79925
unique,NaN,120378,91,13,2,2,2,1377,7195,9,...,1,NaN,8955,69,NaN,1,5787,2,1,1
top,NaN,171-5057375-2831560,05-03-22,Shipped,Amazon,Amazon.in,Expedited,JNE3797,JNE3797-KR-L,Set,...,INR,NaN,BENGALURU,MAHARASHTRA,NaN,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Easy Ship,False
freq,NaN,12,2085,77804,89698,128851,88615,4224,773,50284,...,121180,NaN,11217,22260,NaN,128942,46100,128104,39277,79925
mean,64487.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,648.561465,NaN,NaN,463966.236509,NaN,NaN,NaN,NaN,NaN
std,37232.019822,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,281.211687,NaN,NaN,191476.764941,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,NaN,NaN,110001.000000,NaN,NaN,NaN,NaN,NaN
25%,32243.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,449.000000,NaN,NaN,382421.000000,NaN,NaN,NaN,NaN,NaN
50%,64487.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,605.000000,NaN,NaN,500033.000000,NaN,NaN,NaN,NaN,NaN
75%,96730.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,788.000000,NaN,NaN,600024.000000,NaN,NaN,NaN,NaN,NaN
max,128974.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5584.000000,NaN,NaN,989898.000000,NaN,NaN,NaN,NaN,NaN

In [44]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [45]:
df.duplicated().sum()

0

In [46]:
df[df.duplicated()]

Empty DataFrame
Columns: [index, Order ID, Date, Status, Fulfilment, Sales Channel , ship-service-level, Style, SKU, Category, Size, ASIN, Courier Status, Qty, currency, Amount, ship-city, ship-state, ship-postal-code, ship-country, promotion-ids, B2B, fulfilled-by, Unnamed: 22]
Index: []

[0 rows x 24 columns]

In [47]:
print("For the Continuous Data!")

columns = [
    'Qty',
    'Amount'
]

for col in columns:
    print('\n', '=' * 40)
    print(f"Maximum: {df[col].max():.2f}")
    print(f"Minimum: {df[col].min():.2f}")
    print(f"Average: {df[col].mean():.2f}")
    print(f"Median: {df[col].median():.2f}")
    print(f"Mode: {df[col].mode().iloc[0]:.2f}")
    print(f"Variance: {df[col].var():.2f}")
    print(f"Standard Deviation: {df[col].std():.2f}")
    print(f"Skewness: {df[col].skew():.2f}")

For the Continuous Data!

 ========================================
Maximum: 15.00
Minimum: 0.00
Average: 0.90
Median: 1.00
Mode: 1.00
Variance: 0.10
Standard Deviation: 0.31
Skewness: -0.70

 ========================================
Maximum: 5584.00
Minimum: 0.00
Average: 648.56
Median: 605.00
Mode: 399.00
Variance: 79080.01
Standard Deviation: 281.21
Skewness: 0.89

In [48]:
print("For the Categorical Data!")

columns = [
    'Status',
    'Fulfilment',
    'Sales Channel ',
    'ship-service-level',
    'Category',
    'Size',
    'Courier Status',
    'ship-state',
    'fulfilled-by'
]

for col in columns:
    print('\n', '=' * 40)
    print(df[col].value_counts())

For the Categorical Data!

 ========================================
Status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

 ========================================
Fulfilment
Amazon      89698
Merchant    39277
Name: count, dtype: int64

 ========================================
Sales Channel
Amazon.in     128851
Non-Amazon       124
Name: count, dtype: int64

 ========================================
ship-service-level
Expedited    88615
Standard     40360
Name: count, dtype: int64

 ========================================
Category
Set              50284
kurta            49877
Western Dress    15500
Top              10622
Ethnic Dress      1159
Blouse             926
Bottom             440
Saree              164
Dupatta              3
Name: count, dtype: int64

 ========================================
Size
M       22711
L       22132
XL      20876
XXL     18096
S       17090
3XL     14816
XS      11161
6XL       738
5XL       550
4XL       427
Free      378
Name: count, dtype: int64

 ========================================
Courier Status
Shipped      109487
Unshipped      6681
Cancelled      5935
Name: count, dtype: int64

 ========================================
ship-state
MAHARASHTRA               22260
KARNATAKA                 17326
TAMIL NADU                11483
TELANGANA                 11330
UTTAR PRADESH             10638
                          ...
Mizoram                       1
rajsthan                      1
Punjab/Mohali/Zirakpur        1
Rajsthan                      1
orissa                        1
Name: count, Length: 69, dtype: int64

 ========================================
fulfilled-by
Easy Ship    39277
Name: count, dtype: int64

In [49]:
# ==========================================
#      STEP 2 — Data Quality Check
# ==========================================

In [50]:
df.duplicated().sum()

0

In [51]:
df['Order ID'].duplicated().sum()

8597

In [52]:
df["Order ID"].nunique()

120378

In [53]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [54]:
df['Unnamed: 22']

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
          ...
128970    False
128971    False
128972    False
128973    False
128974    False
Name: Unnamed: 22, Length: 128975, dtype: object

In [55]:
df.drop(columns=['Unnamed: 22'], inplace=True)
print('Your Column has been Successfully Drop!')

Your Column has been Successfully Drop!

In [61]:
total_rows = len(df)

amount_missing = df['Amount'].isna().sum()

amount_available = df['Amount'].notna().sum()

print(f"Total Rows  = {len(df)}")
print(f"Amount Missing = {df['Amount'].isna().sum()}")
print(f"Amount Available = {df['Amount'].notna().sum()}")

Total Rows  = 128975
Amount Missing = 7795
Amount Available = 121180

In [64]:
df.groupby('Status').size()['Cancelled']

18332

In [65]:
df[(df['Amount'].isna()) & (df['Status'] == 'Cancelled')].shape[0]

7566

In [67]:
df['currency'].isnull().sum()

7795

In [69]:
df[df['ship-city'].isnull()]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by
1871,1871,404-0566904-4825137,04-29-22,Shipped,Amazon,Amazon.in,Expedited,J0301,J0301-TP-L,Top,...,1,INR,493.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
1872,1872,404-0566904-4825137,04-29-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-L,kurta,...,1,INR,458.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
8752,8752,406-4003386-8768363,04-25-22,Shipped,Amazon,Amazon.in,Expedited,JNE3376,JNE3376-KR-M,kurta,...,1,INR,432.0,NaN,NaN,NaN,NaN,NaN,False,NaN
11215,11215,402-0107720-7057168,04-23-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,1,INR,654.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
13252,13252,407-4532637-8415521,04-22-22,Cancelled,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,...,0,INR,380.0,NaN,NaN,NaN,NaN,NaN,False,Easy Ship
15688,15688,404-9229894-8608305,04-21-22,Shipped,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-M,kurta,...,1,INR,442.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
16787,16787,402-4919636-4333150,04-20-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE1233,JNE1233-BLUE-KR-031-XXXL,kurta,...,1,INR,376.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
18351,18351,405-4927647-8064368,04-19-22,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-XS,Set,...,1,INR,1112.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
22930,22930,402-8628677-0457954,04-16-22,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,J0003,J0003-SET-S,Set,...,1,INR,654.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
24986,24986,406-4079063-8291520,04-15-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3567,JNE3567-KR-XXL,kurta,...,1,INR,399.0,NaN,NaN,NaN,NaN,NaN,False,NaN
30379,30379,404-7506843-7913132,04-12-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET350,SET350-KR-NP-L,Set,...,1,INR,1299.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
37963,37963,407-3064376-9158743,04-08-22,Cancelled,Merchant,Amazon.in,Standard,JNE3567,JNE3567-KR-M,kurta,...,0,INR,380.0,NaN,NaN,NaN,NaN,NaN,False,Easy Ship
37964,37964,407-3064376-9158743,04-08-22,Cancelled,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,...,0,INR,380.0,NaN,NaN,NaN,NaN,NaN,False,Easy Ship
60986,60986,171-3257610-9237139,05-22-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3365,JNE3365-KR-1052-A-L,kurta,...,1,INR,376.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
63040,63040,402-1049475-3611523,05-20-22,Shipped,Amazon,Amazon.in,Expedited,JNE3739,JNE3739-KR-XXL,kurta,...,1,INR,459.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
73675,73675,405-1356730-8598722,05-11-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET187,SET187-KR-DH-XL,Set,...,1,INR,699.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
73746,73746,407-4664354-2179554,05-11-22,Shipped,Amazon,Amazon.in,Expedited,SET374,SET374-KR-NP-M,Set,...,1,INR,666.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
73771,73771,406-7680604-5439529,05-11-22,Shipped,Amazon,Amazon.in,Expedited,PJNE3607,PJNE3607-KR-4XL,kurta,...,1,INR,869.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
73772,73772,406-7680604-5439529,05-11-22,Shipped,Amazon,Amazon.in,Expedited,PJNE3368,PJNE3368-KR-4XL,kurta,...,1,INR,869.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
73911,73911,405-3420451-5230744,05-11-22,Cancelled,Amazon,Amazon.in,Expedited,SET374,SET374-KR-NP-M,Set,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
80011,80011,171-4552355-0255565,05-07-22,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,SET324,SET324-KR-NP-XL,Set,...,1,INR,607.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
80092,80092,403-2857451-7335536,05-07-22,Shipped,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-S,kurta,...,1,INR,467.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
80455,80455,171-4691098-8489159,05-06-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET183,SET183-KR-DH-M,Set,...,1,INR,759.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
84008,84008,405-8605864-8021901,05-04-22,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,JNE1951,JNE1951-KR-155-XXL,kurta,...,1,INR,368.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
84757,84757,402-8651786-0683548,05-04-22,Shipped,Amazon,Amazon.in,Expedited,JNE3690,JNE3690-TU-XL,Top,...,1,INR,487.0,NaN,NaN,NaN,NaN,NaN,False,NaN
104201,104201,403-3190636-2013146,06-18-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0351,J0351-SET-S,Set,...,1,INR,792.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
106498,106498,402-8673941-7883531,06-16-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3734,JNE3734-KR-XL,kurta,...,0,NaN,NaN,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
124215,124215,405-0340492-2359532,06-04-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3465,JNE3465-KR-L,kurta,...,1,INR,491.0,NaN,NaN,NaN,NaN,NaN,False,NaN
124357,124357,405-5884153-9925116,06-04-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-L,kurta,...,1,INR,486.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
124358,124358,405-5884153-9925116,06-04-22,Shipped,Amazon,Amazon.in,Expedited,SET337,SET337-KR-NP-L,Set,...,1,INR,874.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
124359,124359,405-5884153-9925116,06-04-22,Shipped,Amazon,Amazon.in,Expedited,SET154,SET154-KR-NP-L,Set,...,1,INR,832.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
125385,125385,403-5172380-9787567,06-03-22,Shipped,Amazon,Amazon.in,Expedited,JNE3366,JNE3366-KR-1053-L,kurta,...,1,INR,376.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
126620,126620,403-4249038-6582716,06-02-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3797,JNE3797-KR-M,Western Dress,...,1,INR,735.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship

In [70]:
df['Courier Status'].isnull().sum()

6872

In [84]:
df.groupby('Courier Status').size()[['Unshipped']]

Courier Status
Unshipped    6681
dtype: int64

In [85]:
# ==========================================
#      Step 3 — Data Type & Format Cleaning
# ==========================================

In [86]:
df.dtypes

index                   int64
Order ID               object
Date                   object
Status                 object
Fulfilment             object
Sales Channel          object
ship-service-level     object
Style                  object
SKU                    object
Category               object
Size                   object
ASIN                   object
Courier Status         object
Qty                     int64
currency               object
Amount                float64
ship-city              object
ship-state             object
ship-postal-code      float64
ship-country           object
promotion-ids          object
B2B                      bool
fulfilled-by           object
dtype: object

In [89]:
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')

In [91]:
print(df["Date"].dtype)
print("Invalid Dates:", df["Date"].isna().sum())

datetime64[ns]
Invalid Dates: 0

In [92]:
df['Date'].head()

0   2022-04-30
1   2022-04-30
2   2022-04-30
3   2022-04-30
4   2022-04-30
Name: Date, dtype: datetime64[ns]

In [94]:
df["ship-postal-code"].head(10)

0    400081.0
1    560085.0
2    410210.0
3    605008.0
4    600073.0
5    201102.0
6    160036.0
7    500032.0
8    500008.0
9    600041.0
Name: ship-postal-code, dtype: float64

In [95]:
df["ship-postal-code"]=df["ship-postal-code"].astype('float64').astype('string')

In [100]:
df["ship-postal-code"] = (
    df["ship-postal-code"]
    .str.replace(".0", "", regex=False)
)

In [101]:
print(df["ship-postal-code"].head(10))
print(df["ship-postal-code"].dtype)

0    400081
1    560085
2    410210
3    605008
4    600073
5    201102
6    160036
7    500032
8    500008
9    600041
Name: ship-postal-code, dtype: string
string

In [102]:
print("Qty = 0:", (df["Qty"] == 0).sum())
print("Negative Qty:", (df["Qty"] < 0).sum())

print("Amount = 0:", (df["Amount"] == 0).sum())
print("Negative Amount:", (df["Amount"] < 0).sum())

print("Invalid Dates:", df["Date"].isna().sum())

Qty = 0: 12807
Negative Qty: 0
Amount = 0: 2343
Negative Amount: 0
Invalid Dates: 0

In [103]:
df[df['Qty'] ==0]['Status'].value_counts()

Status
Cancelled                       12701
Shipped                            93
Shipped - Delivered to Buyer        8
Shipped - Returned to Seller        3
Pending                             2
Name: count, dtype: int64

In [104]:
df[df['Amount']==0]['Status'].value_counts()

Status
Shipped                          1518
Shipped - Delivered to Buyer      716
Shipped - Returned to Seller       51
Shipped - Picked Up                28
Pending                            17
Pending - Waiting for Pick Up       9
Shipped - Lost in Transit           2
Shipped - Returning to Seller       2
Name: count, dtype: int64

In [105]:
print("Qty = 0 AND Amount = 0:",
      ((df["Qty"] == 0) & (df["Amount"] == 0)).sum())

Qty = 0 AND Amount = 0: 0

In [106]:
df[
    (df["Qty"] == 0) | (df["Amount"] == 0)
][["Order ID", "Status", "Qty", "Amount"]].head(20)

                Order ID                        Status  Qty   Amount
0    405-8078784-5731545                     Cancelled    0   647.62
3    403-9615377-8133951                     Cancelled    0   753.33
8    407-5443024-5233168                     Cancelled    0      NaN
23   404-6019946-2909948                     Cancelled    0   570.48
29   404-5933402-8801952                     Cancelled    0      NaN
65   171-4137548-0481151                     Cancelled    0      NaN
83   404-6522553-9345930                     Cancelled    0  1105.36
84   403-9950518-0349133                     Cancelled    0      NaN
95   405-9112089-3379536                     Cancelled    0      NaN
101  402-7841951-1872363                     Cancelled    0      NaN
132  171-0293372-4913973                     Cancelled    0      NaN
139  403-6442534-2769112                     Cancelled    0      NaN
155  402-8078642-8565124                     Cancelled    0      NaN
165  406-0218328-1773963                     Cancelled    0      NaN
178  171-1224053-5752314                     Cancelled    0   463.81
205  403-4337144-0984323                     Cancelled    0      NaN
212  408-4547464-4180323  Shipped - Delivered to Buyer    1     0.00
215  403-5456917-5571511                     Cancelled    0      NaN
226  407-4936046-5852304                     Cancelled    0  1249.11
227  407-4936046-5852304                     Cancelled    0  1058.93

In [108]:
df[
    (df["Qty"] == 0) &
    (df["Status"] != "Cancelled")
][["Order ID", "Status", "Qty", "Amount"]].head(20)

                  Order ID                        Status  Qty  Amount
1615   405-7790745-1369118                       Shipped    0     NaN
1989   171-9673855-2321133                       Shipped    0     NaN
2424   404-7478762-7926753                       Shipped    0     NaN
2819   404-0814480-8157169                       Shipped    0     NaN
9255   405-1892033-5435562                       Shipped    0     NaN
11145  404-7498280-7477149                       Shipped    0     NaN
15881  406-5281014-6299540                       Shipped    0     NaN
16191  408-3851867-4615501                       Shipped    0     NaN
16599  403-8676035-5065939                       Shipped    0     NaN
18336  405-1252351-8764324                       Shipped    0     NaN
18891  408-4196439-4813936                       Shipped    0     NaN
18894  408-2656493-8935504  Shipped - Delivered to Buyer    0     NaN
19292  408-0017934-6791513  Shipped - Delivered to Buyer    0     NaN
20402  406-4339807-3944301                       Shipped    0     NaN
20649  402-5900873-2675540                       Shipped    0     NaN
23873  407-5638769-8389162  Shipped - Delivered to Buyer    0     NaN
24270  408-7280154-1992362                       Shipped    0     NaN
24592  406-9799250-9247502                       Shipped    0     NaN
24643  402-3841973-7282702                       Shipped    0     NaN
26028  407-0717613-4338735                       Shipped    0     NaN

In [109]:
print(
    ((df["Qty"] == 0) &
     (df["Status"] != "Cancelled")).sum()
)

106

In [110]:
df[
    (df["Amount"] == 0) &
    (df["Status"] == "Shipped - Delivered to Buyer")
][["Order ID", "Status", "Qty", "Amount"]].head(20)

                 Order ID                        Status  Qty  Amount
212   408-4547464-4180323  Shipped - Delivered to Buyer    1     0.0
388   408-7971979-8745937  Shipped - Delivered to Buyer    1     0.0
441   408-6732772-4525113  Shipped - Delivered to Buyer    1     0.0
729   408-4193711-8156307  Shipped - Delivered to Buyer    1     0.0
947   408-8489677-5577933  Shipped - Delivered to Buyer    1     0.0
986   408-2548158-8811519  Shipped - Delivered to Buyer    1     0.0
1104  408-3011835-7100318  Shipped - Delivered to Buyer    1     0.0
1226  408-5393823-3123507  Shipped - Delivered to Buyer    1     0.0
1254  408-6706673-8229140  Shipped - Delivered to Buyer    1     0.0
1259  408-1088525-0437127  Shipped - Delivered to Buyer    1     0.0
1848  408-2100329-5574743  Shipped - Delivered to Buyer    1     0.0
2038  408-4582558-7314760  Shipped - Delivered to Buyer    1     0.0
2042  408-2677298-4497110  Shipped - Delivered to Buyer    1     0.0
2126  408-4185500-2329134  Shipped - Delivered to Buyer    1     0.0
2139  408-5687276-3227521  Shipped - Delivered to Buyer    1     0.0
2246  408-6177793-2667547  Shipped - Delivered to Buyer    1     0.0
2269  408-2348004-6239507  Shipped - Delivered to Buyer    1     0.0
2295  408-8447246-2180344  Shipped - Delivered to Buyer    1     0.0
2416  408-8659417-9977901  Shipped - Delivered to Buyer    1     0.0
2461  408-9997972-0411544  Shipped - Delivered to Buyer    1     0.0

In [111]:
df[df["Amount"].isna()]["Status"].value_counts()

Status
Cancelled                       7566
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [112]:
df[df["Amount"].isna()][
    ["Order ID", "Status", "Qty", "Amount"]
].head(20)

                Order ID     Status  Qty  Amount
8    407-5443024-5233168  Cancelled    0     NaN
29   404-5933402-8801952  Cancelled    0     NaN
65   171-4137548-0481151  Cancelled    0     NaN
84   403-9950518-0349133  Cancelled    0     NaN
95   405-9112089-3379536  Cancelled    0     NaN
101  402-7841951-1872363  Cancelled    0     NaN
132  171-0293372-4913973  Cancelled    0     NaN
139  403-6442534-2769112  Cancelled    0     NaN
155  402-8078642-8565124  Cancelled    0     NaN
165  406-0218328-1773963  Cancelled    0     NaN
205  403-4337144-0984323  Cancelled    0     NaN
215  403-5456917-5571511  Cancelled    0     NaN
242  404-0634392-1837110  Cancelled    0     NaN
249  404-8514200-3544346  Cancelled    0     NaN
250  404-7452877-2137949  Cancelled    0     NaN
271  404-1607808-0769930  Cancelled    0     NaN
328  402-1365379-0131533  Cancelled    0     NaN
363  171-9620288-8918704  Cancelled    0     NaN
381  404-4026534-0431517  Cancelled    0     NaN
413  171-5542306-9306709  Cancelled    0     NaN

In [113]:
print("Missing Amount:", df["Amount"].isna().sum())

Missing Amount: 7795

In [114]:
df[
    df["Amount"].isna() &
    (df["Status"] != "Cancelled")
][["Order ID", "Status", "Qty", "Amount"]].head(20)

                 Order ID   Status  Qty  Amount
937   S02-5278980-4327051  Shipped   15     NaN
1057  S02-9107114-0460608  Shipped    2     NaN
1615  405-7790745-1369118  Shipped    0     NaN
1989  171-9673855-2321133  Shipped    0     NaN
2424  404-7478762-7926753  Shipped    0     NaN
2819  404-0814480-8157169  Shipped    0     NaN
3631  S02-1006261-5356758  Shipped    9     NaN
3632  S02-3681731-6111841  Shipped    1     NaN
3634  S02-1926028-4838217  Shipped    1     NaN
3636  S02-6828927-1180856  Shipped   13     NaN
3637  S02-3409426-0744131  Shipped    2     NaN
3886  S02-8357726-8633940  Shipped    1     NaN
3887  S02-6358630-3384547  Shipped    1     NaN
3888  S02-8920429-3367507  Shipped    1     NaN
3889  S02-0827522-8659612  Shipped    1     NaN
3890  S02-7924344-3280541  Shipped    1     NaN
3891  S02-7832149-5714447  Shipped    1     NaN
3892  S02-9649067-3246849  Shipped    1     NaN
3893  S02-2310917-8166336  Shipped    1     NaN
3894  S02-0668744-7285638  Shipped    1     NaN

In [115]:
df[df["Amount"].isna() & (df["Qty"] > 0)][
    ["Order ID", "SKU", "Category", "Size", "Qty", "Amount"]
].head(20)

,Order ID,SKU,Category,Size,Qty,Amount
937,S02-5278980-4327051,BL017-63BLACK,Blouse,Free,15,NaN
1057,S02-9107114-0460608,SET315-KR-PP-XL,Set,XL,2,NaN
3631,S02-1006261-5356758,JNE2305-KR-533-L,kurta,L,9,NaN
3632,S02-3681731-6111841,JNE2058-KR-339-L,kurta,L,1,NaN
3634,S02-1926028-4838217,JNE3311-KR-A-XS,kurta,XS,1,NaN
3636,S02-6828927-1180856,JNE2305-KR-533-XXL,kurta,XXL,13,NaN
3637,S02-3409426-0744131,BL020-71RED,Blouse,Free,2,NaN
3886,S02-8357726-8633940,SET251-KR-PP-S,Set,S,1,NaN
3887,S02-6358630-3384547,BL021-71BLACK,Blouse,Free,1,NaN
3888,S02-8920429-3367507,SET304-KR-DPT-XL,Set,XL,1,NaN
3889,S02-0827522-8659612,J0002-SKD-S,Set,S,1,NaN
3890,S02-7924344-3280541,JNE3567-KR-S,kurta,S,1,NaN
3891,S02-7832149-5714447,JNE3405-KR-L,kurta,L,1,NaN
3892,S02-9649067-3246849,JNE3291-KR-L,kurta,L,1,NaN
3893,S02-2310917-8166336,JNE3405-KR-XL,kurta,XL,1,NaN
3894,S02-0668744-7285638,J0012-SKD-XXL,Set,XXL,1,NaN
12974,S02-1862183-4415901,NW008-ST-CP-XXL,Set,XXL,1,NaN
13460,S02-0835825-7267219,NW008-ST-CP-XXL,Set,XXL,1,NaN
13716,S02-7568319-2142153,J0158-DR-XL,Western Dress,XL,1,NaN
13718,S02-9236057-6330320,JNE3571-KR-M,kurta,M,1,NaN

In [116]:
# ==========================================
#  Step 4 — Final Cleaning & Clean Dataset
# ==========================================

In [118]:
df.duplicated().sum()

0

In [119]:
missing = df.isnull().sum()

print(missing[missing > 0])

Courier Status       6872
currency             7795
Amount               7795
ship-city              33
ship-state             33
ship-postal-code       33
ship-country           33
promotion-ids       49153
fulfilled-by        89698
dtype: int64

In [120]:
df["currency"].value_counts(dropna=False)

currency
INR    121180
NaN      7795
Name: count, dtype: int64

In [121]:
df["currency"] = df["currency"].fillna("INR")

In [123]:
df['currency'].value_counts()

currency
INR    128975
Name: count, dtype: int64

In [127]:
df['Courier Status'].value_counts(dropna=False)

Courier Status
Shipped      109487
NaN            6872
Unshipped      6681
Cancelled      5935
Name: count, dtype: int64

In [129]:
print(
    df.loc[df["Courier Status"].isna(), "Status"]
    .value_counts(dropna=False)
)

Status
Cancelled                       6861
Shipped - Delivered to Buyer       8
Shipped - Returned to Seller       3
Name: count, dtype: int64

In [130]:
print(
    df[["ship-city", "ship-state", "ship-postal-code", "ship-country"]]
    .isnull()
    .sum()
)

ship-city           33
ship-state          33
ship-postal-code    33
ship-country        33
dtype: int64

In [131]:
print(
    df.loc[
        df[["ship-city", "ship-state", "ship-postal-code", "ship-country"]]
        .isnull()
        .any(axis=1),
        ["Order ID", "Status", "ship-city", "ship-state",
         "ship-postal-code", "ship-country"]
    ].head(20)
)

                  Order ID                        Status ship-city ship-state  \
1871   404-0566904-4825137                       Shipped       NaN        NaN
1872   404-0566904-4825137                       Shipped       NaN        NaN
8752   406-4003386-8768363                       Shipped       NaN        NaN
11215  402-0107720-7057168                       Shipped       NaN        NaN
13252  407-4532637-8415521                     Cancelled       NaN        NaN
15688  404-9229894-8608305                       Shipped       NaN        NaN
16787  402-4919636-4333150  Shipped - Delivered to Buyer       NaN        NaN
18351  405-4927647-8064368                       Shipped       NaN        NaN
22930  402-8628677-0457954  Shipped - Returned to Seller       NaN        NaN
24986  406-4079063-8291520                     Cancelled       NaN        NaN
30379  404-7506843-7913132  Shipped - Delivered to Buyer       NaN        NaN
37963  407-3064376-9158743                     Cancelled       NaN        NaN
37964  407-3064376-9158743                     Cancelled       NaN        NaN
60986  171-3257610-9237139  Shipped - Delivered to Buyer       NaN        NaN
63040  402-1049475-3611523                       Shipped       NaN        NaN
73675  405-1356730-8598722  Shipped - Delivered to Buyer       NaN        NaN
73746  407-4664354-2179554                       Shipped       NaN        NaN
73771  406-7680604-5439529                       Shipped       NaN        NaN
73772  406-7680604-5439529                       Shipped       NaN        NaN
73911  405-3420451-5230744                     Cancelled       NaN        NaN

      ship-postal-code ship-country
1871              <NA>          NaN
1872              <NA>          NaN
8752              <NA>          NaN
11215             <NA>          NaN
13252             <NA>          NaN
15688             <NA>          NaN
16787             <NA>          NaN
18351             <NA>          NaN
22930             <NA>          NaN
24986             <NA>          NaN
30379             <NA>          NaN
37963             <NA>          NaN
37964             <NA>          NaN
60986             <NA>          NaN
63040             <NA>          NaN
73675             <NA>          NaN
73746             <NA>          NaN
73771             <NA>          NaN
73772             <NA>          NaN
73911             <NA>          NaN

In [132]:
print(
    df[["ship-city", "ship-state", "ship-postal-code", "ship-country"]]
    .isnull()
    .all(axis=1)
    .sum()
)

33

In [133]:
df = df.dropna(
    subset=["ship-city", "ship-state", "ship-postal-code", "ship-country"]
)

In [134]:
df[["ship-city", "ship-state", "ship-postal-code", "ship-country"]].isnull().sum()

ship-city           0
ship-state          0
ship-postal-code    0
ship-country        0
dtype: int64

In [140]:
print(df["promotion-ids"].value_counts(dropna=False).head(20))

promotion-ids
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       49145
IN Core Free Shipping 2015/04/08 23-48-5-108                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              46085
Duplicated A12RHGVGRWOT3S 1560498941486                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     489
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-XX7G3ZRJJJ5LG,Amazon PLCC Free-Financing Universal Merchant AAT-LEHCKNDBJG64E,Amazon PLCC Free-Financing Universal Merchant AAT-DJVHCEV7D7RQY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      458
Duplicated AYTJSBA8ZOP16 1567159860988                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      433
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      316
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      305
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                      230
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-FYWJCQHU2XQ2U,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-URPEBMPS7TSPE,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-YZ2VQO2YM6YYM,Amazon PLCC Free-Financing Universal Merchant AAT-4EOBCMLXMLDGY,Amazon PLCC Free-Financing Universal Merchant AAT-UB6CYNTOQMM7C,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      206
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-YFJA6XMAMWZSK,Amazon PLCC Free-Financing Universal Merchant AAT-K66BSCE2J2V5E,Amazon PLCC Free-Financing Universal Merchant AAT-275LMAQ3T5REI,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      201
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-FYWJCQHU2XQ2U,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-URPEBMPS7TSPE,Amazon PLCC Free-Financing Universal Merchant AAT-YZ2VQO2YM6YYM,Amazon PLCC Free-Financing Universal Merchant AAT-4EOBCMLXMLDGY,Amazon PLCC Free-Financing Universal Merchant AAT-UB6CYNTOQMM7C,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      198

In [141]:
print("Missing:", df["promotion-ids"].isna().sum())
print("Total:", len(df))

Missing: 49145
Total: 128942

In [143]:
df = df.copy()

df["promotion-ids"] = df["promotion-ids"].fillna("No Promotion")

In [144]:
print("Missing:", df["promotion-ids"].isna().sum())
print("Total:", len(df))

Missing: 0
Total: 128942

In [147]:
df['fulfilled-by'].value_counts()

fulfilled-by
Easy Ship    39264
Name: count, dtype: int64

In [148]:
print(
    df.loc[df["fulfilled-by"].isna(), "Status"]
    .value_counts()
)

Status
Shipped      77788
Cancelled    11467
Pending        415
Shipping         8
Name: count, dtype: int64

In [149]:
print(
    df.groupby("Status")["fulfilled-by"]
    .value_counts(dropna=False)
)

Status                         fulfilled-by
Cancelled                      NaN             11467
                               Easy Ship        6858
Pending                        NaN               415
                               Easy Ship         243
Pending - Waiting for Pick Up  Easy Ship         281
Shipped                        NaN             77788
Shipped - Damaged              Easy Ship           1
Shipped - Delivered to Buyer   Easy Ship       28762
Shipped - Lost in Transit      Easy Ship           5
Shipped - Out for Delivery     Easy Ship          35
Shipped - Picked Up            Easy Ship         973
Shipped - Rejected by Buyer    Easy Ship          11
Shipped - Returned to Seller   Easy Ship        1950
Shipped - Returning to Seller  Easy Ship         145
Shipping                       NaN                 8
Name: count, dtype: int64

In [151]:
df['fulfilled-by'] =df['fulfilled-by'].fillna('Unknown')

In [153]:
df['fulfilled-by'].isna().sum()

0

In [154]:
missing =df.isnull().sum()
print(missing[missing>0])

Courier Status    6869
Amount            7793
dtype: int64

In [157]:
print(df.loc[df['Amount'].isna(), 'Status'].value_counts())

Status
Cancelled                       7564
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [158]:
df['Amount'].describe()

count    121149.000000
mean        648.573305
std         281.222115
min           0.000000
25%         449.000000
50%         605.000000
75%         788.000000
max        5584.000000
Name: Amount, dtype: float64

In [159]:
Q1 = df["Amount"].quantile(0.25)
Q3 = df["Amount"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower Bound:", lower)
print("Upper Bound:", upper)

print("Outliers:", ((df["Amount"] < lower) | (df["Amount"] > upper)).sum())

Lower Bound: -59.5
Upper Bound: 1296.5
Outliers: 3599

In [160]:
outliers = df[df["Amount"] > 1296.5]

print(outliers[["Order ID", "Category", "Qty", "Amount", "Status"]].head(20))

                 Order ID Category  Qty   Amount                        Status
102   408-7698765-2294756      Set    1  1338.00  Shipped - Delivered to Buyer
146   171-0131752-2560336      Set    1  1399.00  Shipped - Delivered to Buyer
243   408-2759943-9849959      Set    1  1338.00                       Shipped
265   171-6655820-6440356      Set    2  2130.00                       Shipped
299   404-7491342-1035558      Set    1  1463.00                       Shipped
324   407-5096970-7475550      Set    0  1902.86                     Cancelled
349   171-3537751-4007556      Set    1  1999.00                       Shipped
398   171-2644368-7969167      Set    1  1463.00                       Shipped
416   404-0532727-2082745      Set    1  1499.00                       Shipped
541   406-6993846-8855562      Set    1  1338.00                       Shipped
566   406-8833813-9606757      Set    1  1338.00                       Shipped
647   171-6153595-4758722      Set    2  2224.00                       Shipped
734   406-5700980-4110708      Set    1  1463.00                       Shipped
753   171-4573948-3966741      Set    1  1438.00                       Shipped
803   405-9399780-0313164      Set    1  1669.00                       Shipped
900   405-3139781-4240349      Set    1  1432.00                       Shipped
902   407-4616863-5212363      Set    1  1338.00                       Shipped
955   402-7078622-5609155      Set    1  1432.00  Shipped - Delivered to Buyer
1013  408-3583941-7990727      Set    1  1388.00                       Shipped
1018  171-2730956-8469920      Set    2  1518.00                     Cancelled

In [161]:
print("Outlier Amount Count:", len(outliers))
print("Maximum Outlier Amount:", outliers["Amount"].max())

Outlier Amount Count: 3599
Maximum Outlier Amount: 5584.0

In [162]:
print(
    df.loc[df["Courier Status"].isna(), "Status"]
    .value_counts()
)

Status
Cancelled                       6858
Shipped - Delivered to Buyer       8
Shipped - Returned to Seller       3
Name: count, dtype: int64

In [163]:
print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nMissing Values:")
print(df.isnull().sum()[df.isnull().sum() > 0])
print("\nDuplicate Rows:", df.duplicated().sum())

Rows: 128942
Columns: 23

Missing Values:
Courier Status    6869
Amount            7793
dtype: int64

Duplicate Rows: 0

In [164]:
df.to_csv("amazon_sales_cleaned.csv", index=False)

In [165]:
print("Cleaned Dataset Shape:", df.shape)

Cleaned Dataset Shape: (128942, 23)